const questions = [
    { question: "Quelle est la capitale de la France?", answers: { a: "Berlin", b: "Madrid", c: "Paris", d: "Lisbonne" }, correctAnswer: "c" },
    { question: "Quel est le plus grand océan du monde?", answers: { a: "Océan Atlantique", b: "Océan Arctique", c: "Océan Pacifique", d: "Océan Indien" }, correctAnswer: "c" },
    { question: "Qui a peint la Mona Lisa?", answers: { a: "Vincent Van Gogh", b: "Claude Monet", c: "Leonardo da Vinci", d: "Pablo Picasso" }, correctAnswer: "c" },
    { question: "Quel est l'élément chimique avec le symbole O?", answers: { a: "Or", b: "Oxygène", c: "Osmium", d: "Oxalate" }, correctAnswer: "b" },
    { question: "Quelle est la plus haute montagne du monde?", answers: { a: "K2", b: "Kangchenjunga", c: "Lhotse", d: "Everest" }, correctAnswer: "d" },
    { question: "Combien de continents y a-t-il sur Terre?", answers: { a: "5", b: "6", c: "7", d: "8" }, correctAnswer: "c" },
    { question: "Quelle est la langue la plus parlée au monde?", answers: { a: "Anglais", b: "Espagnol", c: "Chinois mandarin", d: "Hindou" }, correctAnswer: "c" },
    { question: "Qui a écrit 'Roméo et Juliette'?", answers: { a: "Charles Dickens", b: "William Shakespeare", c: "Jane Austen", d: "Mark Twain" }, correctAnswer: "b" },
    { question: "Quel est le plus long fleuve du monde?", answers: { a: "Nil", b: "Amazone", c: "Yangtsé", d: "Mississippi" }, correctAnswer: "a" },
    { question: "Quel est le plus grand désert du monde?", answers: { a: "Sahara", b: "Désert d'Arabie", c: "Gobi", d: "Désert de Kalahari" }, correctAnswer: "a" },
    { question: "Quelle est la capitale de l'Allemagne?", answers: { a: "Vienne", b: "Berlin", c: "Zurich", d: "Hambourg" }, correctAnswer: "b" },
    // Ajoutez ici les autres questions, utilisez le même format
    { question: "Qui a découvert l'Amérique?", answers: { a: "Vasco de Gama", b: "Cristophe Colomb", c: "Marco Polo", d: "James Cook" }, correctAnswer: "b" },
    { question: "Quel est le plus petit pays du monde?", answers: { a: "Monaco", b: "Malte", c: "Vatican", d: "Liechtenstein" }, correctAnswer: "c" },
    { question: "Quelle est la monnaie officielle du Royaume-Uni?", answers: { a: "Euro", b: "Dollar", c: "Livre Sterling", d: "Franc" }, correctAnswer: "c" },
    { question: "Quel est l'animal terrestre le plus rapide?", answers: { a: "Lion", b: "Tigre", c: "Guépard", d: "Léopard" }, correctAnswer: "c" },
    { question: "Quelle est la planète la plus proche du Soleil?", answers: { a: "Venus", b: "Mars", c: "Mercure", d: "Terre" }, correctAnswer: "c" },
    { question: "Quelle est la langue officielle du Brésil?", answers: { a: "Espagnol", b: "Portugais", c: "Français", d: "Anglais" }, correctAnswer: "b" },
    { question: "Quel pays est surnommé le 'Pays du Soleil Levant'?", answers: { a: "Chine", b: "Corée du Sud", c: "Thaïlande", d: "Japon" }, correctAnswer: "d" },
    { question: "Quelle est la capitale de la Russie?", answers: { a: "Saint-Pétersbourg", b: "Minsk", c: "Moscou", d: "Kiev" }, correctAnswer: "c" },
    { question: "Quel est le plus grand lac d'eau douce du monde?", answers: { a: "Lac Supérieur", b: "Lac Victoria", c: "Lac Baïkal", d: "Lac Tanganyika" }, correctAnswer: "c" },
    { question: "Quel est l'organe le plus grand du corps humain?", answers: { a: "Cœur", b: "Foie", c: "Peau", d: "Poumon" }, correctAnswer: "c" },
    { question: "Qui a écrit 'Les Misérables'?", answers: { a: "Émile Zola", b: "Victor Hugo", c: "Gustave Flaubert", d: "Honoré de Balzac" }, correctAnswer: "b" },
    { question: "Quel est le symbole chimique de l'eau?", answers: { a: "H2O", b: "HO2", c: "OH2", d: "H2" }, correctAnswer: "a" },
    { question: "Quelle est la capitale de l'Espagne?", answers: { a: "Barcelone", b: "Valence", c: "Séville", d: "Madrid" }, correctAnswer: "d" },
    { question: "Quelle est la plus grande île du monde?", answers: { a: "Groenland", b: "Madagascar", c: "Borneo", d: "Nouvelle-Guinée" }, correctAnswer: "a" },
    { question: "Quel est le plus grand océan du monde?", answers: { a: "Océan Atlantique", b: "Océan Arctique", c: "Océan Pacifique", d: "Océan Indien" }, correctAnswer: "c" },
    { question: "Qui a écrit 'Guerre et Paix'?", answers: { a: "Fiodor Dostoïevski", b: "Ivan Tourgueniev", c: "Nicolas Gogol", d: "Léon Tolstoï" }, correctAnswer: "d" },
    { question: "Quel est le pays le plus peuplé du monde?", answers: { a: "Inde", b: "États-Unis", c: "Chine", d: "Indonésie" }, correctAnswer: "c" },
    { question: "Quelle est la capitale de l'Italie?", answers: { a: "Milan", b: "Rome", c: "Naples", d: "Turin" }, correctAnswer: "b" },
    { question: "Quel est le plus long fleuve d'Afrique?", answers: { a: "Nil", b: "Congo", c: "Niger", d: "Zambèze" }, correctAnswer: "a" },
    { question: "Qui a inventé l'ampoule électrique?", answers: { a: "Nikola Tesla", b: "Alexander Graham Bell", c: "Thomas Edison", d: "Benjamin Franklin" }, correctAnswer: "c" },
    { question: "Quelle est la capitale du Japon?", answers: { a: "Osaka", b: "Kyoto", c: "Tokyo", d: "Hiroshima" }, correctAnswer: "c" },
    { question: "Quel est le plus grand désert chaud du monde?", answers: { a: "Désert d'Arabie", b: "Désert de Gobi", c: "Désert de Kalahari", d: "Sahara" }, correctAnswer: "d" },
    { question: "Qui a peint la fresque de la Chapelle Sixtine?", answers: { a: "Raphaël", b: "Michel-Ange", c: "Léonard de Vinci", d: "Donatello" }, correctAnswer: "b" },
    { question: "Quel est le plus grand pays du monde par superficie?", answers: { a: "Canada", b: "Chine", c: "États-Unis", d: "Russie" }, correctAnswer: "d" },
    { question: "Quelle est la plus longue chaîne de montagnes du monde?", answers: { a: "Himalaya", b: "Rocheuses", c: "Andes", d: "Alpes" }, correctAnswer: "c" },
    { question: "Quel est le plus grand mammifère terrestre?", answers: { a: "Éléphant d'Afrique", b: "Baleine bleue", c: "Rhinocéros blanc", d: "Hippopotame" }, correctAnswer: "a" },
];
